version: '3.4'

name: vidsnap

services:
  sql-db:
    container_name: vidsnap-database
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04    
    restart: always
    networks:
      - vidsnap-net
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Senha@12345
    ports:
      - 1433:1433
    volumes:
      - sql-db-volume:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Senha@12345 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  web-api:
    container_name: vidsnap-web-api
    build:
      context: .
      dockerfile: infra.web-api/Vidsnap.API/Dockerfile
    image: vidsnap-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 8080:8080
      - 8081:8081
    restart: on-failure
    networks:
      - vidsnap-net
    depends_on:
      - sql-db

volumes:
  sql-db-volume: {}

networks:
  vidsnap-net:
    driver: bridge
